export const dataAbout = [
  {
    id: 0,
    head: "Codepolitan",
    text: "Kursus ini memberikan saya pengalaman dan pembelajaran yang baik sebagai fullstack developer.",
    src: "/img/codepolitan-logo.png",
  },
  {
    id: 1,
    head: "Freecodecamp",
    text: "  Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta,minus voluptatem quaerat assumenda totam natus beatae quod eveniet? Esse, quos?",
    src: "/img/fcp.png",
  },
  {
    id: 2,
    head: "Mengenal Pemrograman Komputer",
    text: "  Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta,minus voluptatem quaerat assumenda totam natus beatae quod eveniet? Esse, quos?",
    src: "/img/6SMW2KK - Mengenal Pemrograman Komputer.jpg",
  },
];

export const dataProject = [
  {
    id: 0,
    head: "AniSite",
    title: "Anime, manga site",
    src: "/anisite.jpg",
    language: "React Js",
    show: "https://ani-site-seven.vercel.app/",
    category: "web2",
  },
  {
    id: 1,
    head: "Burger App",
    title: "Create Burger App",
    src: "/burgerApp.jpg",
    language: "React js",
    show: "https://burger-app-sigma.vercel.app/",
    category: "web2",
  },
  {
    id: 2,
    head: "Create Table",
    title: "Table Price",
    src: "/img-pj/table-pricing.png",
    language: "html, css",
    show: "https://isfndiar.github.io/table-pricing/",
    category: "web2",
  },
  {
    id: 3,
    head: "Niaba boster",
    title: "Hosting, deploy web for free (Landing Page)",
    src: "/niababoster.jpg",
    language: "html, css",
    show: "https://isfndiar.github.io/niagahoster-pages/",
    category: "web2",
  },
  {
    id: 4,
    head: "first Portfolio",
    title: "portofolio with html,css,js",
    src: "/portfolio1.jpg",
    language: "html, css,js",
    show: "https://isfndiar.github.io/portfolio/",
    category: "web2",
  },
  {
    id: 5,
    head: "Create Table",
    title: "lorem ipsum bang udah bang",
    src: "/img-pj/table-pricing.png",
    language: "html, css",
  },
];
