export const dataAbout = [
  {
    id: 0,
    year: "2022 - now",
    head: "Codepolitan",
    text: "studied at codepolitan. provide good experience and learning in fullstack developer",
    src: "/img/codepolitan-logo.png",
  },
  {
    id: 1,
    year: "2020 - now",
    head: "Freecodecamp",
    text: "studied at Freecodecamp. provide good experience and learning in terms of programming logic and algorithms",
    src: "/img/fcp.png",
  },
  {
    id: 2,
    year: "2020 - now",
    head: "Freecodecamp",
    text: "studied at Freecodecamp. provide good experience and learning in terms of programming logic and algorithms",
    src: "/img/fcp.png",
  },
  {
    id: 3,
    year: "2020 - now",
    head: "Freecodecamp",
    text: "studied at Freecodecamp. provide good experience and learning in terms of programming logic and algorithms",
    src: "/img/fcp.png",
  },
  {
    id: 4,
    year: "2020 - now",
    head: "Freecodecamp",
    text: "studied at Freecodecamp. provide good experience and learning in terms of programming logic and algorithms",
    src: "/img/fcp.png",
  },
  {
    id: 5,
    year: "2020 - now",
    head: "Freecodecamp",
    text: "studied at Freecodecamp. provide good experience and learning in terms of programming logic and algorithms",
    src: "/img/fcp.png",
  },
];

export const dataProject = [
  {
    id: 0,
    head: "AniSite",
    title: "Anime, manga site",
    src: "/anisite.jpg",
    language: "React Js",
    show: "https://ani-site-seven.vercel.app/",
    category: "web2",
  },
  {
    id: 1,
    head: "Burger App",
    title: "Create Burger App",
    src: "/burgerApp.jpg",
    language: "React js",
    show: "https://burrgerapp.vercel.app/",
    category: "web2",
  },
  {
    id: 2,
    head: "Create Table",
    title: "Table Price",
    src: "/img-pj/table-pricing.png",
    language: "html, css",
    show: "https://isfndiar.github.io/table-pricing/",
    category: "web2",
  },
  {
    id: 3,
    head: "DiarHoster",
    title: "Hosting, deploy web for free (Landing Page)",
    src: "/niababoster.jpg",
    language: "html, css",
    show: "https://isfndiar.github.io/niagahoster-pages/",
    category: "web2",
  },
  {
    id: 4,
    head: "first Portfolio",
    title: "portofolio with html,css,js",
    src: "/portfolio1.jpg",
    language: "html, css,js",
    show: "https://isfndiar.github.io/portfolio/",
    category: "web2",
  },
];
